import { StyleSheet } from "react-native";

export const Cores = {
  fundo: "#0F172A",
  fundoCard: "#1E293B",
  card: "#334155",
  primaria: "#38BDF8",
  primariaEscura: "#0284C7",
  verde: "#34D399",
  vermelho: "#F87171",
  texto: "#F8FAFC",
  textoSuave: "#94A3B8",
  borda: "#334155",
};

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: Cores.fundo,
  },
  pagina: {
    flex: 1,
    padding: 20,
    backgroundColor: Cores.fundo,
  },
  tituloTela: {
    fontSize: 26,
    fontWeight: "bold",
    color: Cores.texto,
    textAlign: "center",
    marginBottom: 6,
  },
  subtitulo: {
    fontSize: 15,
    color: Cores.textoSuave,
    textAlign: "center",
    marginBottom: 40,
  },
  cardStatus: {
    backgroundColor: Cores.card,
    borderRadius: 24,
    paddingVertical: 48,
    paddingHorizontal: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Cores.borda,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
    width: "100%",
    maxWidth: 360,
  },
  cardInfo: {
    backgroundColor: Cores.card,
    borderRadius: 24,
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Cores.borda,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
    width: "100%",
    maxWidth: 360,
  },
  textoMovimento: {
    fontSize: 28,
    fontWeight: "700",
    textAlign: "center",
    color: Cores.texto,
    marginTop: 16,
  },
  textoParado: {
    color: Cores.texto,
  },
  textoDetectado: {
    color: Cores.verde,
  },
  indicador: {
    width: 18,
    height: 18,
    borderRadius: 9,
    marginBottom: 12,
  },
  indicadorParado: {
    backgroundColor: Cores.textoSuave,
  },
  indicadorDetectado: {
    backgroundColor: Cores.verde,
    shadowColor: Cores.verde,
    shadowOpacity: 0.9,
    shadowRadius: 12,
    elevation: 6,
  },
  labelStatus: {
    fontSize: 14,
    color: Cores.textoSuave,
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 8,
  },
  containerTeste: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    backgroundColor: Cores.fundo,
  },
  cardTeste: {
    backgroundColor: Cores.card,
    borderRadius: 24,
    paddingVertical: 40,
    paddingHorizontal: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Cores.borda,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
    width: "100%",
    maxWidth: 360,
  },
  textoTeste: {
    fontSize: 22,
    fontWeight: "700",
    color: Cores.texto,
    textAlign: "center",
  },
  botao: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 20,
    minHeight: 50,
    width: "100%",
    maxWidth: 360,
    marginTop: 12,
  },
  botaoPrimario: {
    backgroundColor: Cores.primaria,
  },
  botaoSecundario: {
    backgroundColor: Cores.card,
    borderWidth: 1,
    borderColor: Cores.borda,
  },
  botaoDesabilitado: {
    opacity: 0.4,
  },
  textoBotao: {
    fontSize: 16,
    fontWeight: "700",
    color: Cores.texto,
    marginLeft: 8,
  },
  textoBotaoPrimario: {
    color: Cores.fundo,
  },
  botaoVoltar: {
    marginTop: 24,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  textoVoltar: {
    fontSize: 15,
    color: Cores.textoSuave,
    textAlign: "center",
  },
  linhaInfo: {
    width: "100%",
    marginTop: 16,
    alignItems: "center",
  },
  labelInfo: {
    fontSize: 13,
    color: Cores.textoSuave,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  valorInfo: {
    fontSize: 20,
    fontWeight: "700",
    color: Cores.texto,
    textAlign: "center",
  },
  aviso: {
    fontSize: 14,
    color: Cores.textoSuave,
    textAlign: "center",
    marginTop: 12,
  },
  statusPermissao: {
    fontSize: 14,
    color: Cores.vermelho,
    textAlign: "center",
    marginTop: 16,
    maxWidth: 360,
  },
  textoVazio: {
    fontSize: 16,
    color: Cores.textoSuave,
    textAlign: "center",
    marginTop: 48,
  },
});